// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"time"

	"github.com/SpectatorNan/gorm-zero/gormc"

	"github.com/SpectatorNan/gorm-zero/gormc/pagex"
	"gorm.io/gorm"
)

type (
	playerModel interface {
		Insert(ctx context.Context, tx *gorm.DB, data *Player) error
		BatchInsert(ctx context.Context, tx *gorm.DB, news []Player) error
		FindOne(ctx context.Context, id int64) (*Player, error)
		FindPageList(ctx context.Context, page *pagex.ListReq, orderBy pagex.OrderBy,
			orderKeys map[string]string, whereClause func(db *gorm.DB) *gorm.DB) ([]Player, int64, error)
		FindOneByAccountIdServerId(ctx context.Context, accountId uint64, serverId uint64) (*Player, error)
		FindOneByNicknameHash(ctx context.Context, nicknameHash uint64) (*Player, error)
		FindOneByPlayerId(ctx context.Context, playerId uint64) (*Player, error)
		Update(ctx context.Context, tx *gorm.DB, data *Player) error
		BatchUpdate(ctx context.Context, tx *gorm.DB, olds, news []Player) error
		BatchDelete(ctx context.Context, tx *gorm.DB, datas []Player) error

		Delete(ctx context.Context, tx *gorm.DB, id int64) error
	}

	defaultPlayerModel struct {
		conn  *gorm.DB
		table string
	}

	Player struct {
		Id           int64     `gorm:"column:id;primary_key"` // 自增id
		CreatedAt    time.Time `gorm:"column:created_at"`     // 创建时间
		UpdatedAt    time.Time `gorm:"column:updated_at"`     // 更新时间
		AccountId    uint64    `gorm:"column:account_id"`     // 账户ID
		ServerId     uint64    `gorm:"column:server_id"`      // 服务器id
		PlayerId     uint64    `gorm:"column:player_id"`      // 玩家id
		Level        uint64    `gorm:"column:level"`          // 玩家等级
		Nickname     string    `gorm:"column:nickname"`       // 昵称
		NicknameHash uint64    `gorm:"column:nickname_hash"`  // 昵称hash
		Avatar       string    `gorm:"column:avatar"`         // 头像
		Exp          uint64    `gorm:"column:exp"`            // 经验
	}
)

func (Player) TableName() string {
	return "`player`"
}

func newPlayerModel(db *gorm.DB) *defaultPlayerModel {
	return &defaultPlayerModel{
		conn:  db,
		table: "`player`",
	}
}

func (m *defaultPlayerModel) Insert(ctx context.Context, tx *gorm.DB, data *Player) error {
	db := m.conn
	if tx != nil {
		db = tx
	}
	err := db.WithContext(ctx).Create(&data).Error
	return err
}
func (m *defaultPlayerModel) BatchInsert(ctx context.Context, tx *gorm.DB, news []Player) error {
	db := m.conn
	if tx != nil {
		db = tx
	}
	err := db.Create(&news).Error
	return err
}

func (m *defaultPlayerModel) FindOne(ctx context.Context, id int64) (*Player, error) {
	var resp Player
	err := m.conn.WithContext(ctx).Model(&Player{}).Where("`id` = ?", id).Take(&resp).Error
	switch err {
	case nil:
		return &resp, nil
	case gormc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}
func (m *defaultPlayerModel) FindPageList(ctx context.Context, page *pagex.ListReq, orderBy pagex.OrderBy,
	orderKeys map[string]string, whereClause func(db *gorm.DB) *gorm.DB) ([]Player, int64, error) {
	conn := m.conn
	formatDB := func() (*gorm.DB, *gorm.DB) {
		db := conn.Model(&Player{})
		if whereClause != nil {
			db = whereClause(db)
		}
		return db, nil
	}

	res, total, err := pagex.FindPageListWithCount[Player](ctx, page, orderBy, orderKeys, formatDB)
	return res, total, err
}

func (m *defaultPlayerModel) FindOneByAccountIdServerId(ctx context.Context, accountId uint64, serverId uint64) (*Player, error) {
	var resp Player
	err := m.conn.WithContext(ctx).Model(&Player{}).Where("`account_id` = ? and `server_id` = ?", accountId, serverId).Take(&resp).Error
	switch err {
	case nil:
		return &resp, nil
	case gormc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPlayerModel) FindOneByNicknameHash(ctx context.Context, nicknameHash uint64) (*Player, error) {
	var resp Player
	err := m.conn.WithContext(ctx).Model(&Player{}).Where("`nickname_hash` = ?", nicknameHash).Take(&resp).Error
	switch err {
	case nil:
		return &resp, nil
	case gormc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPlayerModel) FindOneByPlayerId(ctx context.Context, playerId uint64) (*Player, error) {
	var resp Player
	err := m.conn.WithContext(ctx).Model(&Player{}).Where("`player_id` = ?", playerId).Take(&resp).Error
	switch err {
	case nil:
		return &resp, nil
	case gormc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPlayerModel) Update(ctx context.Context, tx *gorm.DB, data *Player) error {
	db := m.conn
	if tx != nil {
		db = tx
	}
	err := db.WithContext(ctx).Save(data).Error
	return err
}
func (m *defaultPlayerModel) BatchUpdate(ctx context.Context, tx *gorm.DB, olds, news []Player) error {
	db := m.conn
	if tx != nil {
		db = tx
	}
	err := db.WithContext(ctx).Save(&news).Error

	return err
}

func (m *defaultPlayerModel) Delete(ctx context.Context, tx *gorm.DB, id int64) error {
	db := m.conn
	if tx != nil {
		db = tx
	}
	err := db.WithContext(ctx).Delete(&Player{}, id).Error

	return err
}

func (m *defaultPlayerModel) BatchDelete(ctx context.Context, tx *gorm.DB, datas []Player) error {
	db := m.conn
	if tx != nil {
		db = tx
	}
	err := db.Delete(&datas).Error
	return err
}
