// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"time"

	"github.com/SpectatorNan/gorm-zero/gormc"

	"github.com/SpectatorNan/gorm-zero/gormc/pagex"
	"gorm.io/gorm"
)

type (
	playerItemModel interface {
		Insert(ctx context.Context, tx *gorm.DB, data *PlayerItem) error
		BatchInsert(ctx context.Context, tx *gorm.DB, news []PlayerItem) error
		FindOne(ctx context.Context, id int64) (*PlayerItem, error)
		FindPageList(ctx context.Context, page *pagex.ListReq, orderBy pagex.OrderBy,
			orderKeys map[string]string, whereClause func(db *gorm.DB) *gorm.DB) ([]PlayerItem, int64, error)
		FindOneByInstanceId(ctx context.Context, instanceId string) (*PlayerItem, error)
		Update(ctx context.Context, tx *gorm.DB, data *PlayerItem) error
		BatchUpdate(ctx context.Context, tx *gorm.DB, olds, news []PlayerItem) error
		BatchDelete(ctx context.Context, tx *gorm.DB, datas []PlayerItem) error

		Delete(ctx context.Context, tx *gorm.DB, id int64) error
	}

	defaultPlayerItemModel struct {
		conn  *gorm.DB
		table string
	}

	PlayerItem struct {
		Id          int64     `gorm:"column:id;primary_key"` // 自增id
		CreatedAt   time.Time `gorm:"column:created_at"`     // 创建时间
		UpdatedAt   time.Time `gorm:"column:updated_at"`     // 更新时间
		ServerId    uint64    `gorm:"column:server_id"`      // 服务器id
		PlayerId    uint64    `gorm:"column:player_id"`      // 玩家id
		ItemId      uint64    `gorm:"column:item_id"`        // 道具id
		Type        uint64    `gorm:"column:type"`           // 道具类型
		SubType     uint64    `gorm:"column:sub_type"`       // 道具子类型
		Count       uint64    `gorm:"column:count"`          // 数量
		IsStackable uint64    `gorm:"column:is_stackable"`   // 是否可叠加
		InstanceId  string    `gorm:"column:instance_id"`    // 唯一实例id
	}
)

func (PlayerItem) TableName() string {
	return "`player_item`"
}

func newPlayerItemModel(db *gorm.DB) *defaultPlayerItemModel {
	return &defaultPlayerItemModel{
		conn:  db,
		table: "`player_item`",
	}
}

func (m *defaultPlayerItemModel) Insert(ctx context.Context, tx *gorm.DB, data *PlayerItem) error {
	db := m.conn
	if tx != nil {
		db = tx
	}
	err := db.WithContext(ctx).Create(&data).Error
	return err
}
func (m *defaultPlayerItemModel) BatchInsert(ctx context.Context, tx *gorm.DB, news []PlayerItem) error {
	db := m.conn
	if tx != nil {
		db = tx
	}
	err := db.Create(&news).Error
	return err
}

func (m *defaultPlayerItemModel) FindOne(ctx context.Context, id int64) (*PlayerItem, error) {
	var resp PlayerItem
	err := m.conn.WithContext(ctx).Model(&PlayerItem{}).Where("`id` = ?", id).Take(&resp).Error
	switch err {
	case nil:
		return &resp, nil
	case gormc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}
func (m *defaultPlayerItemModel) FindPageList(ctx context.Context, page *pagex.ListReq, orderBy pagex.OrderBy,
	orderKeys map[string]string, whereClause func(db *gorm.DB) *gorm.DB) ([]PlayerItem, int64, error) {
	conn := m.conn
	formatDB := func() (*gorm.DB, *gorm.DB) {
		db := conn.Model(&PlayerItem{})
		if whereClause != nil {
			db = whereClause(db)
		}
		return db, nil
	}

	res, total, err := pagex.FindPageListWithCount[PlayerItem](ctx, page, orderBy, orderKeys, formatDB)
	return res, total, err
}

func (m *defaultPlayerItemModel) FindOneByInstanceId(ctx context.Context, instanceId string) (*PlayerItem, error) {
	var resp PlayerItem
	err := m.conn.WithContext(ctx).Model(&PlayerItem{}).Where("`instance_id` = ?", instanceId).Take(&resp).Error
	switch err {
	case nil:
		return &resp, nil
	case gormc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPlayerItemModel) Update(ctx context.Context, tx *gorm.DB, data *PlayerItem) error {
	db := m.conn
	if tx != nil {
		db = tx
	}
	err := db.WithContext(ctx).Save(data).Error
	return err
}
func (m *defaultPlayerItemModel) BatchUpdate(ctx context.Context, tx *gorm.DB, olds, news []PlayerItem) error {
	db := m.conn
	if tx != nil {
		db = tx
	}
	err := db.WithContext(ctx).Save(&news).Error

	return err
}

func (m *defaultPlayerItemModel) Delete(ctx context.Context, tx *gorm.DB, id int64) error {
	db := m.conn
	if tx != nil {
		db = tx
	}
	err := db.WithContext(ctx).Delete(&PlayerItem{}, id).Error

	return err
}

func (m *defaultPlayerItemModel) BatchDelete(ctx context.Context, tx *gorm.DB, datas []PlayerItem) error {
	db := m.conn
	if tx != nil {
		db = tx
	}
	err := db.Delete(&datas).Error
	return err
}
